<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <GenerateProgramFile>true</GenerateProgramFile>
    <TargetFramework>net9.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="IOS.fs" />
    <Compile Include="Computer.fs" />
    <Compile Include="Network.fs" />
  </ItemGroup>

</Project>
